board/accounts/tour/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("common/", include("common.urls")),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("recommend_app/", include("recommend_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("home_app/",include("home_app.urls"))


    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

dist_app/urls.py
from django.urls import path
from . import views

app_name = 'dist_app'

urlpatterns = [
    path("index/",views.index, name = "index"),
    path("index2/",views.index_2, name = "index2"),
    path("index3/",views.index_3, name = "index3"),
    path("marker/",views.marker, name = "marker"),
    path('jeju/', views.jeju, name='jeju'),
    path('aewol/', views.aewol, name='aewol'),
    path('hanlim/', views.hanlim, name='hanlim'),
    path('hankyung/', views.hankyung, name='hankyung'),
    path('daejung/', views.daejung, name='daejung'),
    path('andeok/', views.andeok, name='andeok'),
    path('jungmun/', views.jungmun, name='jungmun'),
    path('seogwipo/', views.seogwipo, name='seogwipo'),
    path('namwon/', views.namwon, name='namwon'),
    path('pyosun/', views.pyosun, name='pyosun'),
    path('seongsan/', views.seongsan, name='seongsan'),
    path('gujwa/', views.gujwa, name='gujwa'),
    path('jocheon/', views.jocheon, name='jocheon'),
]

tour/urls.py
from django.contrib import admin
from django.urls import path,include
from home_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("",include("home_app.urls")),
    path("", views.index, name="index"),
    path("mypage_app/",include("mypage_app.urls")),
    path("board/", include("board.urls")),



    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

dist_app/models.py
from django.db import models

# Create your models here.

dist_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'dist_app/dist_app.html')

def index_2(request):
    return render(request, 'dist_app/dist_app_2.html')

def index_3(request):
    return render(request, 'dist_app/dist_app_3.html')

def marker(request):
    return render(request, 'dist_app/dist_app_marker.html')

def jeju(request):
    return render(request, 'dist_app/1_jeju.html')

def aewol(request):
    return render(request, 'dist_app/2_aewol.html')

def hanlim(request):
    return render(request, 'dist_app/3_hanlim.html')

def hankyung(request):
    return render(request, 'dist_app/4_hankyung.html')

def daejung(request):
    return render(request, 'dist_app/5_daejung.html')

def andeok(request):
    return render(request, 'dist_app/6_andeok.html')

def jungmun(request):
    return render(request, 'dist_app/7_jungmun.html')

def seogwipo(request):
    return render(request, 'dist_app/8_seogwipo.html')

def namwon(request):
    return render(request, 'dist_app/9_namwon.html')

def pyosun(request):
    return render(request, 'dist_app/10_pyosun.html')

def seongsan(request):
    return render(request, 'dist_app/11_seongsan.html')

def gujwa(request):
    return render(request, 'dist_app/12_gujwa.html')

def jocheon(request):
    return render(request, 'dist_app/13_jocheon.html')

dist_app/templates/dist_app/dist_app_marker.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h2>오늘은 어디로 갈까?</h2>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


<a href="{% url 'dist_app:index' %}">뚜벅이</a>
<a href="{% url 'dist_app:marker' %}">여행지추천</a>


<script>
// 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
var infowindow = new kakao.maps.InfoWindow({zIndex:1});

var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

// 지도를 생성합니다
var map = new kakao.maps.Map(mapContainer, mapOption);

// 장소 검색 객체를 생성합니다
var ps = new kakao.maps.services.Places(map);

// 카테고리로 은행을 검색합니다
ps.categorySearch('BK9', placesSearchCB, {useMapBounds:true});

// 키워드 검색 완료 시 호출되는 콜백함수 입니다
function placesSearchCB (data, status, pagination) {
    if (status === kakao.maps.services.Status.OK) {
        for (var i=0; i<data.length; i++) {
            displayMarker(data[i]);
        }
    }
}

// 지도에 마커를 표시하는 함수입니다
function displayMarker(place) {
    // 마커를 생성하고 지도에 표시합니다
    var marker = new kakao.maps.Marker({
        map: map,
        position: new kakao.maps.LatLng(place.y, place.x)
    });

    // 마커에 클릭이벤트를 등록합니다
    kakao.maps.event.addListener(marker, 'click', function() {
        // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
        infowindow.setContent('<div style="padding:5px;font-size:12px;">' + place.place_name + '</div>');
        infowindow.open(map, marker);
    });
}
</script>


<link rel="stylesheet" href="{% static 'dist_app/index.css'%}">
    <div id="recommendation">
        <fieldset id="fs" style="height:20; width: 65%; border: 1px solid; margin-left: 300px;">
            <legend id="jeju_text"> JEJU ISLAND </legend>
            <input type="radio" name="radio" value="제주시" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/jeju/';"> 제주시 &emsp;
            <input type="radio" name="radio" value="애월" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/aewol/';"> 애월 &emsp;
            <input type="radio" name="radio" value="한림" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/hanlim/';"> 한림 &emsp;
            <input type="radio" name="radio" value="한경" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/hankyung/';"> 한경 &emsp;
            <input type="radio" name="radio" value="대정" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/daejung/';"> 대정 &emsp;
            <input type="radio" name="radio" value="안덕" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/andeok/';"> 안덕 &emsp;
            <input type="radio" name="radio" value="중문" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/jungmun/';" > 중문 &emsp;
            <input type="radio" name="radio" value="서귀포시" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/seogwipo/';"> 서귀포시 &emsp;
            <input type="radio" name="radio" value="남원" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/namwon/';"> 남원 &emsp;
            <input type="radio" name="radio" value="표선" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/pyosun/';"> 표선 &emsp;
            <input type="radio" name="radio" value="성산" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/seongsan/';" > 성산 &emsp;
            <input type="radio" name="radio" value="구좌" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/gujwa/';"> 구좌 &emsp;
            <input type="radio" name="radio" value="조천" OnClick="window.location.href='http://127.0.0.1:8000/dist_app/jocheon/';"> 조천 &emsp;
        </fieldset>


        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'scripts.js' %}"></script>





{% endblock %}