board/accounts/tour/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("common/", include("common.urls")),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("recommend_app/", include("recommend_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("home_app/",include("home_app.urls"))


    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

board/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login_1.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    path('<int:board_id>/create_reply', views.create_reply, name='create_reply'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('edit/<int:pk>', views.edit, name='edit'),

]

tour/urls.py
from django.contrib import admin
from django.urls import path,include
from home_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("",include("home_app.urls")),
    path("", views.index, name="index"),
    path("mypage_app/",include("mypage_app.urls")),
    path("board/", include("board.urls")),



    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

board/accounts/models.py
from django.db import models

# Create your models here.

board/models.py
from django.db import models
from django.contrib.auth.models import User


class Board(models.Model):
    """
        title: 제목
        content: 내용
        author: 작성자
        like_count: 좋아요 카운트
        pub_date: 배포일
    """
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    like_count = models.PositiveIntegerField(default=0) # 양수입력 필드
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title

class Reply(models.Model):
    """
        reply: Reply -> Board 연결관계
        comment: 댓글내용
        rep_date: 작성일
    """
    author = models.ForeignKey(Board, on_delete=models.CASCADE,null=True)
    comment = models.CharField(max_length=200)
    rep_date = models.DateTimeField()

    def __str__(self):
        return self.comment

board/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')
    class Meta:
        model = User
        fields = ('username', 'email')

board/accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

# Create your views here.
from django.template import RequestContext

from accounts.forms import UserForm





#users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect


def signup(request):
    if request.method == 'POST':
        # 회원가입에 필요한 코드 작성
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/index')
    else:
        # 회원가입 폼을 응답한다.
        form = UserForm()
    return render(request, 'accounts/signup_1.html', {'form': form})

board/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .models import Board


@login_required(login_url='accounts:login')
def index(request):
    all_boards = Board.objects.all().order_by("-pub_date")  # 모든 데이터 조회, 내림차순(-표시) 조회
    paginator = Paginator(all_boards, 5)
    page = int(request.GET.get('page', 1))
    board_list = paginator.get_page(page)
    return render(request, 'board/index.html', {'title': 'Board List', 'board_list': board_list})


@login_required(login_url='accounts:login')
def detail(request, board_id):
    board = Board.objects.get(id=board_id)
    return render(request, 'board/detail.html', {'board': board})

@login_required(login_url='accounts:login')
def write(request):
    return render(request, 'board/write.html')

@login_required(login_url='accounts:login')
def write_board(request):
    b = Board(title=request.POST['title'], content=request.POST['detail'], author=request.user, pub_date=timezone.now())
    b.save()
    return HttpResponseRedirect(reverse('board:index'))

@login_required(login_url='accounts:login')
def create_reply(request, board_id):
    b = Board.objects.get(id = board_id)
    b.reply_set.create(comment=request.POST['comment'], rep_date=timezone.now(), author = request.user)
    return HttpResponseRedirect(reverse('board:detail', args=(board_id,)))


@login_required(login_url='accounts:login')
def delete(request, pk):
    post = Board.objects.get(id=pk)
    post.delete()
    return redirect('board')

@login_required(login_url='accounts:login')
def edit(request, pk):
    board = Board.objects.get(id=pk)
    if request.method == "POST":
        board.title = request.POST['title']
        board.content = request.POST['content']
        board.writer = request.POST['writer']

        board.save()
        return redirect('board')

    else:
        boardForm = Board
        return render(request, 'update.html', {'boardForm':boardForm})

schedule_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView

from . import models
from .models import Adddate, Hotplace
from django.contrib.auth.decorators import login_required


@login_required(login_url='accounts:login')
def index(request):
    return render(request, 'schedule_app/schedule_list.html')


def schedulelist(request):
    during = Adddate.objects.filter(author_id=request.user)

    return render(request, 'schedule_app/schedule_list.html', {'during': during})


# def finallist(request):
#     place_list = Hotplace.objects.filter(tour=Adddate.objects.filter(author_id=request.user))
#     return render(request, 'schedule_app/schedule_list.html', {'place_list': place_list})

def finallist(request):
    hotplace_list = Hotplace.objects.filter(place_author_id=request.user).order_by('days')
    return render(request, 'schedule_app/schedule_list.html', {'hotplace_list': hotplace_list})


def create(request):
    during = Adddate(during=request.GET.get('during'), author=request.user)
    during.save()

    during1 = request.GET.get('during')
    days = list(range(int(during1)))
    days1 = []
    for i in days:
        days1.append(i + 1)

    return render(request, 'schedule_app/schedule_list.html', {'day': days1, 'tour_id': during.pk})
    # return redirect('/schedule_app/list')


def day(request):
    if request.GET.get('place') != None:
        place = Hotplace(tour_place=request.GET.get('place'), days=request.GET.get('test'), tour_id=request.GET.get('fk'), place_author=request.user)
        place.save()

        return redirect('/schedule_app/finallist')


def delete(request, place_author_ad):
    place_list = Hotplace.objects.get(id=place_author_ad)
    place_list.delete()
    return redirect('/schedule_app/finallist')

board/templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'board/detail.css' %}">
<header class="masthead" style="background-image: url('http://wetravel.cafe24.com/data/editor/1808/20180802112254_c4835f6ce5c51f178656a5ecd3471d53_d9c1.png')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
							<span class="subheading">TODAY TOUR</span>
                            <h2 id="ocean"> 바다의 속삭임이 좋아요 </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<div class="content">

	<div id="home">
		<a href="{% url 'board:index' %}"><u>> Home</u></a>
	</div>

	<div>
		<table class="board_for_read" >
			<tbody>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">제목</td>
					<td style="padding:10px;">
						<input type="text" name="title" id="title" value="{{ board.title }}" readonly/>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">작성일자</td>
					<td style="padding:10px; color: gray;">
						<span>{{ board.pub_date }}</span>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center;">내용</td>
					<td style="padding:10px;">
						<textarea name="detail" id="detail" rows="10" readonly>{{ board.content }}</textarea>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

		<form action="{% url 'board:create_reply' board.id %}" method="post">
		{% csrf_token %}
		<br>
		<table class="board_for_read">
			<tbody>
				<tr>
					<td colspan="2" class="td_title">leave a comment</td>
				</tr>
				<tr>
					<td style="text-align:center;">
						<input type="text" name="comment" id="comment" style="width:1100px">
					</td>
					<td><input type="submit" value="save"></td>
				</tr>
			</tbody>
		</table>
		</form>

		<div class="reply_content">
			{% for rep in board.reply_set.all %}
				<span class="reply"><u>{{ rep.comment }} [{{ rep.rep_date|date:'Y-m-d H:i'}}]</u></span>
			{% endfor %}
		</div>
    </div>

{% endblock %}

board/templates/board/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'board/index.css' %}">
<header class="masthead" style="background-image: url('http://wetravel.cafe24.com/data/editor/1808/20180802112254_c4835f6ce5c51f178656a5ecd3471d53_d9c1.png')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
							<span class="subheading" style="color: orange;">TODAY TOUR</span>
                            <h2 id="ocean" style="font-size:35px; margin-top: 10px;"> 바다의 속삭임이 좋아요 </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<div class="content">
        <div class="header">
            <h2 id="h2"> 혼자 옵서예 <span id="injeju">IN JEJU</span> </h2>
        </div>
        <div id="write">
            <a href="{% url 'board:write' %}" id="text_write" style="font-size:15px;"><u><b>글쓰기</b></u></a>
        </div>

        <div style="height:280px;">
            <table class="board" style="width:1200;">
                <thead>
                    <tr class="header" id="header">
                        <th style="width:10%;">순번</th>
                        <th style="width:60%">제목</th>
                        <th style="width:20%">작성자</th>
                        <th style="width:30%">작성일자</th>
                    </tr>
                </thead>
                <tbody>
                {% if board_list %}
                    {% for data in board_list %}
                    <tr class="{% cycle '' 'even_bgcolor' %}">
                        <td style="text-align:center;">{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'board:detail' data.id %}">
                                {{ data.title }}
                            </a>
                        </td>
                        <td>{{ data.author }}</td>
                        <td>{{ data.pub_date|date:'Y-m-d' }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>작성된 게시글이 없습니다.</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <div style="text-align:center">
            <div class="pagination">
                <div style="width:40%; margin: 5px;">
                {% if board_list.has_previous %}
                    <a class="abutton" href="?page=1" style="font-size: 15px; background-color:white;"><u>맨앞으로</u></a>  &nbsp;
                    <a class="abutton" href="?page={{ board_list.previous_page_number }}" style="font-size: 15px; background-color:white;"><u>이전</u></a>
                {% endif %}
                </div>

                <div style="width:30%; margin: 5px; font-size:25px; font-family: 'Jua', sans-serif;">
                {% for page in board_list.paginator.page_range %}
                    {% if page >= board_list.number|add:-2 and page <= board_list.number|add:2 %}
                    <span class="{% if page == board_list.number %}current{% endif %}">
                        <a id="num" href="?page={{ page }}">{{ page}}</a>
                    </span>
                    {% elif page >= board_list.number|add:-3 and page <= board_list.number|add:3 %}
                        ..
                    {% endif %}
                {% endfor %}
                </div>

                <div style="width:35%; margin: 5px;">
                {% if board_list.has_next %}
                    <a class="abutton" href="?page={{ board_list.next_page_number }}"  style="font-size: 15px; background-color:white;"><u>다음</u></a>  &nbsp;
                    <a class="abutton" href="?page={{ board_list.paginator.num_pages }}"  style="font-size: 15px; background-color:white;"><u>맨뒤로</u></a>
                {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

board/templates/board/update.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'board/index.css' %}">
<header class="masthead" style="background-image: url('http://wetravel.cafe24.com/data/editor/1808/20180802112254_c4835f6ce5c51f178656a5ecd3471d53_d9c1.png')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
							<span class="subheading">TODAY TOUR</span>
                            <h2 id="ocean"> 바다의 속삭임이 좋아요 </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>

<div class="container" style="max-width:500px;">
	<form method="POST">
	  {% csrf_token %}
	  {% bootstrap_form boardForm %}
	  <input class="btn btn-dark rounded-pill col-12" type="submit" value="수정하기" onclick="location.href='/edit/{{board.pk}}/'">
  </form>
</div>

{% endblock %}

board/templates/board/write.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'board/write.css' %}">

<header class="masthead" style="background-image: url('http://wetravel.cafe24.com/data/editor/1808/20180802112254_c4835f6ce5c51f178656a5ecd3471d53_d9c1.png')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
							<span class="subheading">TODAY TOUR</span>
                            <h2 id="ocean"> 바다의 속삭임이 좋아요 </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<div class="content">
		<form action="{% url 'board:write_board' %}" method="post">
		{% csrf_token %}

		<div id="home">
			<a href="{% url 'board:index' %}"> <u>> Home</u></a>
		</div>
		<br>
<div id="sj">
	<label> 제목 </label>
	<input id="td" type="text" name="title" id="title" value="{{ board.title }}" style="border: 0;"/> <br><br>
	<label> 내용 </label>
	<textarea id="td" name="detail" id="detail" rows="10">{{ board.content }}</textarea>
</div>

		<div id="save">
			<input id="save1" type="submit" value="저장" style="background-color:rgb(46, 39, 130);">
		</div>
		</form>
    </div>

	<script src="{% static 'write.js' %}"></script>
{% endblock %}