accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login_1.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

board/accounts/tour/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("common/", include("common.urls")),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("recommend_app/", include("recommend_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("home_app/",include("home_app.urls"))


    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

board/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login_1.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

tour/urls.py
from django.contrib import admin
from django.urls import path,include
from home_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("",include("home_app.urls")),
    path("", views.index, name="index"),
    path("mypage_app/",include("mypage_app.urls")),
    path("board/", include("board.urls")),



    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

board/accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')
    class Meta:
        model = User
        fields = ('username', 'email')

board/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')
    class Meta:
        model = User
        fields = ('username', 'email')

accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

# Create your views here.
from django.template import RequestContext

from accounts.forms import UserForm





#users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect


def signup(request):
    if request.method == 'POST':
        # 회원가입에 필요한 코드 작성
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/index')
    else:
        # 회원가입 폼을 응답한다.
        form = UserForm()
    return render(request, 'accounts/signup_1.html', {'form': form})

board/accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

# Create your views here.
from django.template import RequestContext

from accounts.forms import UserForm





#users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect


def signup(request):
    if request.method == 'POST':
        # 회원가입에 필요한 코드 작성
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/index')
    else:
        # 회원가입 폼을 응답한다.
        form = UserForm()
    return render(request, 'accounts/signup_1.html', {'form': form})

accounts/templates/accounts/form_errors.html
{% extends "base.html" %}
{% block content %}
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/login.css' %}">
<!-- Page Header-->
        <header class="masthead" style="background-image: url('https://www.popco.net/zboard/data/dica_forum_samsung/2015/07/27/147743295955b5c369685cd.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <span class="subheading">TODAY TOUR</span>
                            <h2 id="jeju"> 떠나요 제주도 >_< </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>

<div class="container my-3">
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div id="Btn">
            <button type="submit" class="btn btn-primary">로그인</button>
            <button class="btn btn-primary"><a href="{% url 'accounts:signup'%}">회원가입</a></button>
        </div>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login_1.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/login_1.css' %}">
<!-- Page Header-->
        <header class="masthead" style="background-image: url('https://www.popco.net/zboard/data/dica_forum_samsung/2015/07/27/147743295955b5c369685cd.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <span class="subheading">TODAY TOUR</span>
                            <h2 id="jeju"> 떠나요 제주도 >_< </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>

<p id="sign-up"> <b>LOGIN</b> </p> <br>
<div id="img_1">
    <img id="img1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx11GFBGQW9hy-KQbb-CQ6haFRIdM0Tem_r5jjrwOTYD84UT4NF64xjfsN-f8kTeY4DKs&usqp=CAU" alt="jeju_flower">
    <img id="img2" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx11GFBGQW9hy-KQbb-CQ6haFRIdM0Tem_r5jjrwOTYD84UT4NF64xjfsN-f8kTeY4DKs&usqp=CAU" alt="jeju_flower">
</div>
<div class="container my-3">
    <div id="login_box">
        <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label style="margin-right:50px;" for="username">ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">PASSWORD</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <div id="Btn">
                <button style="background-color: rgb(238, 130, 148); border: none;" type="submit" class="btn btn-primary">로그인</button>
                <button style="background-color: rgb(238, 130, 148); border: none;" class="btn btn-primary"><a href="{% url 'accounts:signup'%}">회원가입</a></button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/login.css' %}">
<!-- Page Header-->
        <header class="masthead" style="background-image: url('https://www.popco.net/zboard/data/dica_forum_samsung/2015/07/27/147743295955b5c369685cd.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <span class="subheading">TODAY TOUR</span>
                            <h2 id="jeju"> 떠나요 제주도 >_< </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<div class="container my-3">
    <form method="post" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary" id="Btn">생성하기</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup_1.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/signup.css' %}">
<!-- Page Header-->
        <header class="masthead" style="background-image: url('https://www.popco.net/zboard/data/dica_forum_samsung/2015/07/27/147743295955b5c369685cd.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <span class="subheading">TODAY TOUR</span>
                            <h2 id="jeju"> 떠나요 제주도 >_< </h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <p id="sign-up"> <b>SIGN UP</b> </p> <br>
          <div class="container my-3">
            <form method="post" action="{% url 'accounts:signup' %}">
                {% csrf_token %}
                {% include "form_errors.html" %}

                <div class="mb-3">
                    <label for="username">
                        <p id="p">ID</p>
                        <input type="text" class="form-control" name="username" id="username">
                    </label>
                </div>

                <div class="mb-3">
                    <label for="password1">
                        <p id="p">PASSWORD</p>
                        <input type="password" class="form-control" name="password1" id="password1">
                    </label>
                </div>

                <div class="mb-3">
                    <label for="password2">
                        <p id="p">PASSWORD CHECK</p>
                        <input type="password" class="form-control" name="password2" id="password2">
                    </label>
                </div>

                <div class="mb-3">
                    <label for="email">
                        <p id="p">EMAIL</p>
                        <input type="text" class="form-control" name="email" id="email">
                    </label>
                </div>

                <button type="submit" class="btn btn-primary" id="Btn" style="background-color: rgb(238, 130, 148); border: none;">같이가자 :)</button>
            </form>
        </div>



{% endblock %}