accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login_1.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

board/accounts/tour/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("common/", include("common.urls")),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("recommend_app/", include("recommend_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("home_app/",include("home_app.urls"))


    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    path('<int:board_id>/create_reply', views.create_reply, name='create_reply'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('edit/<int:pk>', views.edit, name='edit'),

]

dist_app/urls.py
from django.urls import path
from . import views

app_name = 'dist_app'

urlpatterns = [
    path("index/",views.index, name = "index"),
    path("index2/",views.index_2, name = "index2"),
    path("index3/",views.index_3, name = "index3"),
    path("marker/",views.marker, name = "marker"),
    path('jeju/', views.jeju, name='jeju'),
    path('aewol/', views.aewol, name='aewol'),
    path('hanlim/', views.hanlim, name='hanlim'),
    path('hankyung/', views.hankyung, name='hankyung'),
    path('daejung/', views.daejung, name='daejung'),
    path('andeok/', views.andeok, name='andeok'),
    path('jungmun/', views.jungmun, name='jungmun'),
    path('seogwipo/', views.seogwipo, name='seogwipo'),
    path('namwon/', views.namwon, name='namwon'),
    path('pyosun/', views.pyosun, name='pyosun'),
    path('seongsan/', views.seongsan, name='seongsan'),
    path('gujwa/', views.gujwa, name='gujwa'),
    path('jocheon/', views.jocheon, name='jocheon'),
]

home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path("index/",views.index, name='index'),

]

tour/urls.py
from django.contrib import admin
from django.urls import path,include
from home_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("dist_app/", include("dist_app.urls")),
    path("schedule_app/", include("schedule_app.urls")),
    path("",include("home_app.urls")),
    path("", views.index, name="index"),
    path("mypage_app/",include("mypage_app.urls")),
    path("board/", include("board.urls")),



    # path('dist_app/', include('dist_app.urls')),
    # path('home/', include('home_app.urls')),
    # path('mypage/', include('mypage.urls')),
    # path('recommend_app/', include('recommend_app.urls')),
    # path('schdule_app/', include('schdule_app.urls'))
]

common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")

common/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
        {% include 'navbar.html' %}
    <body>

    {% block content %}


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'scripts.js' %}"></script>
            <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'scripts.js' %}"></script>
    {% endblock %}
    </body>

</html>

common/templates/form_errors.html
{% if form.errors%}
{%for field in form%}
{%for error in field.errors%}
<div class="alert alert-danger">
    <strong>{{field.label}}</strong>
    {{error}}

</div>
{%endfor%}
{%endfor%}
{%for error in form.non_field_error%}
<div class="alert alert-danger">
    <strong>{{error}}</strong>
</div>
{%endfor%}
{%endif%}

common/templates/navbar.html
{% load static %}
<!--Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home_app:index' %}">오늘 Tour(O<sub>2</sub>)</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home_app:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'schedule_app:index' %}">여행스케줄러</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'dist_app:index' %}">여행추천</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'board:index' %}">여행게시판</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'mypage_app:index' %}">나의정보</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:logout' %}">{{user}}님 로그아웃</a></li>  <!--True 일때 실행-->
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:login' %}">로그인</a></li>  <!--False 일때 실행-->

                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>